services:
  mp2i-bot:
    build:
      target: production

  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    volumes:
      - ${PWD}/external_data:/data
      - ${PWD}/filebrowser_config:/config
    env_file:
      - ${PWD}/.env
    restart: always
    expose:
      - 8080
    hostname: mp2i-bot-filebrowser

  webhook:
    image: lwlook/webhook
    volumes:
      - ${PWD}:/app
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9000
    hostname: mp2i-bot-webhook
    command: -verbose -hooks=/app/webhook/hooks.yml -hotreload -template
    env_file:
      - ${PWD}/.env
