services:
  mp2i-bot:
    user: 0:0
    build:
      target: debug
    restart: "no"
    ports:
      - 5678:5678
    develop:
      watch:
        - action: sync
          path: ${PWD}/src
          target: /app
        - action: rebuild
          path: ${PWD}/uv.lock
        - action: rebuild
          path: ${PWD}/config.toml
        - action: rebuild
          path: ${PWD}/.env
